require('dotenv').config()
const app = require('./app')

app.listen(process.env.PORT, () => {
  console.log('████████████████████████████████████')
  console.log('███                              ███')
  console.log('███           MD Server          ███')
  console.log('███                              ███')
  console.log('████████████████████████████████████')
  console.log(`Puerto: ${process.env.PORT}`)
  console.log('Access Token Expires:')
  console.log(`  - ${process.env.ACCESS_TOKEN_EXPIRES_IN} segundos`)
  console.log(`  - ${process.env.ACCESS_TOKEN_EXPIRES_IN / 60} minutos`)
  console.log(`  - ${process.env.ACCESS_TOKEN_EXPIRES_IN / 60 / 60} horas`)
  console.log(`  - ${process.env.ACCESS_TOKEN_EXPIRES_IN / 60 / 60 / 24} dias`)
  console.log(`http://localhost:${process.env.PORT}`)
  console.log(`${process.env.HOST}`)
})
